name: Generate Snake

on:
  schedule: 
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Mr-RK-3009
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          message: "Generate Snake"
          add: "dist/github-contribution-grid-snake.svg"
